version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - WEBHOOK_URL=${WEBHOOK_URL}

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PROXY_PASS_URL=http://backend:8000
    depends_on:
      - backend
